#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the miniMaxSum function below.
def miniMaxSum(arr):
    min1=min(arr)
    max1=max(arr)
    arrsum=sum(arr)
    print(arrsum-max1,arrsum-min1)
             

if __name__ == '__main__':
    arr = list(map(int, input().rstrip().split()))

    miniMaxSum(arr)
